# Generated by Django 3.2.8 on 2021-10-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dev_api', models.CharField(max_length=550)),
                ('medium_api', models.CharField(max_length=550)),
                ('hashnode_api', models.CharField(max_length=550)),
            ],
        ),
    ]
