# Generated by Django 3.2.8 on 2021-10-26 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('notion_Oauth', models.CharField(max_length=550)),
                ('notion_pg_id', models.CharField(max_length=550)),
                ('notion_db_id', models.CharField(max_length=550)),
            ],
        ),
    ]
