# Generated by Django 3.2.8 on 2021-10-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0002_integration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='integration',
            new_name='integrationModel',
        ),
    ]
