# Generated by Django 3.2.8 on 2021-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0003_rename_integration_integrationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistoremodel',
            name='dev_api',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='apistoremodel',
            name='hashnode_api',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='apistoremodel',
            name='medium_api',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
