# Generated by Django 3.2.8 on 2021-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0005_apistoremodel_sync_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apistoremodel',
            name='sync_url',
        ),
        migrations.AddField(
            model_name='integrationmodel',
            name='sync_url',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
